### ISSUE TITLE
Dockerfile is not building properly for action 

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/sentinel-forward-data-action#7]
I tried to use the action externally, in which case it build the dockerfile and the error I am getting back is

```
python: can't open file '/github/workspace/src/action.py': [Errno 2] No such file or directory
```

https://github.com/cds-snc/sre-bot/actions/runs/3888775732/jobs/6636433855#step:6:9

I think something is not quite right with how the dockerfile builds. 

It might also make sense to have just a ci_build workflow to check of the dockerfile continues to build properly, which may catch changes if we somehow break it in the future.

**Comment by sylviamclaughlin** [comment]
@maxneuvians There is a new [PR](https://github.com/cds-snc/sentinel-forward-data-action/pull/8) that I created that I "think" addresses the issues as far as I can tell from all of my testing. 
Also, looking at how you are using the action, the passed in filename you are passing in (ossf-results.json), I will need to change the github action to account for this since right now the action reads in each line in a file and puts it in Sentinel. Is ossf-results.json just a big json object? Or is each line a json object? Right now the action should work for the latter but not for the first case.

**Comment by sylviamclaughlin** [comment]
Issue has been resolved.
